### PR TITLE
proxy: ensure conn is always non-nil

### LINKED ISSUE #181: Panic when closing a connection
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Close a client connection and fetch the ClientAddr() in `OnConnClose()`.

### 2. What did you expect to see? (Required)

The address is right.

### 3. What did you see instead (Required)

Panic.
Because the `PacketIO.conn` is set to nil after closing.

### 4. What is your version? (Required)

master

### PR DESCRIPTION
**Pull request by xhebox**
Signed-off-by: xhe <xw897002528@gmail.com>

### What problem does this PR solve?

Issue Number: close #181

Problem Summary: Ensure it is always non-nil, while eliminated `double close` issue. Note that is OK to call `XXXAddr` after connection is closed.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Notable changes

- [ ] Has configuration change
- [ ] Has HTTP API interfaces change (Don't forget to [add the declarative for API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- [ ] Has tiproxyctl change
- [ ] Other user behavior changes

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/proxy/net/packetio.go [hunk 1]
```diff
@@ -262,10 +262,7 @@ func (p *PacketIO) Flush() error {
 }
 
 func (p *PacketIO) GracefulClose() error {
-	if p.conn != nil {
-		return p.conn.SetDeadline(time.Now())
-	}
-	return nil
+	return p.conn.SetDeadline(time.Now())
```
Comment (djshow832) [inline pkg/proxy/net/packetio.go:265]: It's possible that GracefulClose may be called after Close, so I added the judgement.

**Review by djshow832 — COMMENTED** [review]
Please always add some test cases.

**Review by disksing — APPROVED** [review]

File: pkg/proxy/net/packetio.go (hunk 1 above)
Comment (xhebox) [reply pkg/proxy/net/packetio.go]: OK, so it also ignored `ErrClosed`.

**Review by djshow832 — APPROVED** [review]
