### PR TITLE
config: skip irrelevant config file events

### LINKED ISSUE #321: TiProxy infinitely reloads the config file
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Use the config file in the working directory.

```sh
cp conf/proxy.toml .
./bin/tiproxy --config=proxy.toml > proxy.log
```

### 2. What did you expect to see? (Required)

The file size of `proxy.log` is small.

### 3. What did you see instead (Required)

The file size of `proxy.log` keeps increasing rapidly. The logs are all about reloading the config file.
The event of the config file is `event="WRITE         \"proxy.log\""`, which means the log file is modified but the config file is not.

### 4. What is your version? (Required)

master

OS: macOS

### PR DESCRIPTION
**Pull request by djshow832**
### What problem does this PR solve?

Issue Number: close #321

Problem Summary:
- If the log file is in the same directory as the config file, TiProxy reloads the config file once the log outputs, and reloading itself causes log output, which is a dead loop.
- If the directory is removed and then both the directory and the file are created within 200ms, the ConfigManager doesn't receive an event.

What is changed and how it works:
- Check the file name for the watch event
- Reload events if watch list is empty before adding
- Support searching logger for test

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Notable changes

- [ ] Has configuration change
- [ ] Has HTTP API interfaces change
- [ ] Has tiproxyctl change
- [ ] Other user behavior changes

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: lib/util/logger/logger.go [hunk 1]
```diff
@@ -12,18 +14,33 @@ import (
...
 	return zap.New(zapcore.NewCore(
 		zapcore.NewConsoleEncoder(zap.NewDevelopmentEncoderConfig()),
-		zapcore.AddSync(&testingLog{t}),
+		zapcore.AddSync(&testingLog{T: t}),
 		zap.InfoLevel,
 	)).Named(t.Name())
 }
+
+// CreateLoggerAndStringerForTest returns both the logger and its content.
+func CreateLoggerAndStringerForTest(t *testing.T) (*zap.Logger, fmt.Stringer) {
```
Comment (xhebox) [inline lib/util/logger/logger.go:39]: I think it is identical as `CreateLoggerForTest`? Maybe:

1. define `CreateLoggerForTest` as `lg, _ := CreateLoggerAndStringerForTest()`.
2. replace `CreateLoggerForTest` with `CreateLoggerAndStringerForTest`

**Review by xhebox — COMMENTED** [review]
Test failed

File: pkg/manager/config/config_test.go [hunk 2]
```diff
@@ -153,8 +154,133 @@ func TestConfigRemove(t *testing.T) {
...
+		{
+			// Test relative path.
+			filename: "./cfg",
+		},
+		{
+			// Test uncleaned path.
+			filename: fmt.Sprintf("%s%c%ccfg", tmpdir, filepath.Separator, filepath.Separator),
+		},
+		{
+			// Test removing and creating the directory.
```
Comment (xhebox) [inline pkg/manager/config/config_test.go:222]: There is a need to `removing and recreating the file`

**Review by xhebox — COMMENTED** [review]
Rest LGTM

File: pkg/manager/config/config_test.go (hunk 2 above)
Comment (djshow832) [reply pkg/manager/config/config_test.go]: Addressed.

**Review by xhebox — APPROVED** [review]
