### PR TITLE
router, backend: stop retrying connecting to backends if the fetcher fails

### LINKED ISSUE #179: Stop retrying connecting to backends if the fetcher fails
## Development Task

Currently, when the backend fetcher returns an empty backend list, the proxy keeps retrying for 5 seconds.
However, the serverless tier may encounter some problems that can't be recovered immediately. In this case, the fetcher can return an error, indicating that the proxy doesn't need to retry.

### PR DESCRIPTION
**Pull request by djshow832**
### What problem does this PR solve?

Issue Number: close #179

Problem Summary:
Currently, when the backend fetcher returns an empty backend list, the proxy keeps retrying for 5 seconds.
However, the serverless tier may encounter some problems that can't be recovered immediately. In this case, the fetcher can return an error, indicating that the proxy doesn't need to retry.

What is changed and how it works:
- Add a return value of `error` type for `BackendFetcher.GetBackendList()`
- Add the return value for `Observer`, `BackendEventReceiver`, `BackendSelector`, and so on
- Stop retrying connecting if the error is not nil

Note that https://github.com/pingcap/TiProxy/issues/180 will be fixed in another PR.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Notable changes

- [ ] Has configuration change
- [ ] Has HTTP API interfaces change (Don't forget to [add the declarative for API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- [ ] Has tiproxyctl change
- [ ] Other user behavior changes

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/manager/router/backend_observer.go [hunk 1]
```diff
@@ -178,13 +180,26 @@ func (bo *BackendObserver) Refresh() {
...
 	for ctx.Err() == nil {
-		backendInfo := bo.fetcher.GetBackendList(ctx)
-		backendStatus := bo.checkHealth(ctx, backendInfo)
-		if ctx.Err() != nil {
-			return
+		backendInfo, err := bo.fetcher.GetBackendList(ctx)
+		if err == nil {
+			if lastErr != nil {
+				bo.logger.Info("fetching backends succeeds now")
+				bo.eventReceiver.OnObserveError(err)
```
Comment (xhebox) [inline pkg/manager/router/backend_observer.go:189]: How about use only callback `OnObserve(map[string]XXX, error)` or `OnObserve(ObserveEvent)`?
I feel it is a little bit complicated that `backendChangeEvent` and `backendChangeErrorEvent` are parallel.

It seems more reasonable to invoke `OnXXXEvent` everytime:
1. polled the fetcher, and something is returned
2. gateway asynchronizely pushed some events to the observer
