### PR TITLE
log: print welcom after config init

### LINKED ISSUE #453: Welcome log is not printed in tiup cluster
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Issue Number: close #453

Problem Summary: The root cause that tiup-cluster did not print the welcome log is that, tiproxy prints the message to stdout, which goes to system units.

And it is basically impossible/very hard to redirect that to the log file on tiup-cluster. Instead, we just print the log after config initialization,

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Notable changes

- [ ] Has configuration change
- [ ] Has HTTP API interfaces change
- [ ] Has tiproxyctl change
- [ ] Other user behavior changes

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/server/server.go [hunk 1]
```diff
@@ -70,6 +69,8 @@ func NewServer(ctx context.Context, sctx *sctx.Context) (srv *Server, err error)
 	}
 	cfg := srv.ConfigManager.GetConfig()
 
+	printInfo(lg)
```
Comment (djshow832) [inline pkg/server/server.go:72]: Add some comments. I'm afraid someone will revert it in the future.

Comment (xhebox) [reply pkg/server/server.go:75]: Done

**Review by djshow832 — APPROVED** [review]
